# Parameter Configuration File for MPC Trajectory Generator

# ROS Topic Names
pose_topic: "pf/pose/odom"
drive_topic: "nav"

# Visualization
visualization_enabled: true

# Input CSV File Path
csv_path_inner: "/home/yash/yasht_ws/src/mpc_av/Csv Files/MPC_innerline.csv"
csv_path_center: "/home/yash/yasht_ws/src/mpc_av/Csv Files/MPC_centerline_1.csv"
csv_path_outer: "/home/yash/yasht_ws/src/mpc_av/Csv Files/MPC_outerline.csv"

# Car Parameters:
# Speed Variations
high_speed: 5
medium_speed: 2
low_speed: 1

# Tracking Parameter
lookahead_distance: 2.2

# Parallel Offset for lookahead
parallel_offset: 1.2

# Local Map Distance
local_map_distance: 3.0

# Inflation Radius
inflation_radius: 4

# No of Collision Checks
n_collision_checks: 20

# Raceline Type
# 0 - Inner Line
# 1 - Center Line
# 2 - Outer Line
# 3 - Get the Best WayPoints from the 3 Racelines Online (Allows Obstacle Avoidance)
raceline_type: 2